on:
  workflow_dispatch:
    inputs:
      new_repo_name:
        description: 'Name of the new repository'
        required: true
      new_repo_description:
        description: 'Description of the new repository'
        required: false
        default: ''
      visibility:
        description: 'Repository visibility (public/private)'
        required: true
        default: 'private'
      include_all_branches:
        description: 'Include all branches'
        required: true
        default: 'false'

jobs:
  create_repo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create repository from template
      env:
        GH_TOKEN: ${{ secrets.REPO_CREATION_TOKEN }}
      run: |
        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository_owner }}/template-repo/generate \
          -f "owner=${{ github.repository_owner }}" \
          -f "name=${{ github.event.inputs.new_repo_name }}" \
          -f "description=${{ github.event.inputs.new_repo_description }}" \
          -F "include_all_branches=${{ github.event.inputs.include_all_branches }}" \
          -F "private=${{ github.event.inputs.visibility == 'private' }}"

    - name: Set branch protection rules
      run: |
        # Set protection for main branch
        gh api repos/${{ github.repository }}/branches/main/protection \
          --method PUT \
          -f required_status_checks='{"strict": true, "contexts": []}' \
          -f enforce_admins=true \
          -f required_pull_request_reviews='{"dismissal_restrictions": {}, "dismiss_stale_reviews": true, "require_code_owner_reviews": true, "required_approving_review_count": 1}' \
          -f restrictions=null

        # Set protection for dev branch (if it exists)
        if gh api repos/${{ github.repository }}/branches/dev &> /dev/null; then
          gh api repos/${{ github.repository }}/branches/dev/protection \
            --method PUT \
            -f required_status_checks='{"strict": true, "contexts": []}' \
            -f enforce_admins=true \
            -f required_pull_request_reviews='{"dismissal_restrictions": {}, "dismiss_stale_reviews": true, "require_code_owner_reviews": true, "required_approving_review_count": 1}' \
            -f restrictions=null
        fi

        # Set branch deletion rules (prevent deletion of protected branches)
        gh api repos/${{ github.repository }} \
          --method PATCH \
          -f delete_branch_on_merge=false

      env:
        GITHUB_TOKEN: ${{ secrets.REPO_CREATION_TOKEN }}
