on:
  workflow_dispatch:
    inputs:
      new_repo_name:
        description: 'Name of the new repository'
        required: true
      new_repo_description:
        description: 'Description of the new repository'
        required: false
        default: ''
      visibility:
        description: 'Repository visibility (public/private)'
        required: true
        default: 'private'
      include_all_branches:
        description: 'Include all branches'
        required: true
        default: 'false'

jobs:
  create_repo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create repository from template
      env:
        GH_TOKEN: ${{ secrets.REPO_CREATION_TOKEN }}
      run: |
        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository_owner }}/template-repo/generate \
          -f "owner=${{ github.repository_owner }}" \
          -f "name=${{ github.event.inputs.new_repo_name }}" \
          -f "description=${{ github.event.inputs.new_repo_description }}" \
          -F "include_all_branches=${{ github.event.inputs.include_all_branches }}" \
          -F "private=${{ github.event.inputs.visibility == 'private' }}"

    - name: Set branch protection rules
      run: |
        # Set protection for main branch
        gh api \
          --method PUT \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          repos/${{ github.repository }}/branches/main/protection \
          -F "required_status_checks[strict]=true" -F "enforce_admins=true" -F "required_pull_request_reviews[dismiss_stale_reviews]=true" -F "required_pull_request_reviews[require_code_owner_reviews]=true" -F "required_pull_request_reviews[required_approving_review_count]=2" -F "required_pull_request_reviews[require_last_push_approval]=true" -F "required_linear_history=true" -F "lock_branch=true" -F "required_conversation_resolution=true" -F "allow_fork_syncing=true"

        # Set protection for dev branch (if it exists)
        if gh api repos/${{ github.repository }}/branches/dev &> /dev/null; then
          gh api \
            --method PUT \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            repos/${{ github.repository }}/branches/dev/protection \
            -F "required_status_checks[strict]=true" -F "enforce_admins=true" -F "required_pull_request_reviews[dismiss_stale_reviews]=true" -F "required_pull_request_reviews[require_code_owner_reviews]=true" -F "required_pull_request_reviews[required_approving_review_count]=2" -F "required_pull_request_reviews[require_last_push_approval]=true" -F "required_linear_history=true" -F "required_conversation_resolution=true" -F "allow_fork_syncing=true"
        fi

        # Set branch deletion rules (prevent deletion of protected branches)
        gh api repos/${{ github.repository }} \
          --method PATCH \
          -f delete_branch_on_merge=false

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
